using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http; // Required for IFormFile

namespace BackendApi.Models
{
    // DTO for receiving post creation data from the form
    public class CreatePostDto
    {
        [Required]
        public string Title { get; set; } = string.Empty;

        [Required]
        public DateTime DatePublished { get; set; } // Changed back to DateTime

        public string? Timeline { get; set; }

        [Required]
        public string Story { get; set; } = string.Empty;

        public string? WorkCited { get; set; }

        // Note: ImageURL is handled separately after upload
        // Note: CreatedAt is set server-side
        // Note: PostId is generated by the database
    }
}
